import React, { useEffect, useRef, useState } from 'react'
import { ApiError, api, RecordItem, Session } from '../api'
import { ErrorMessage, Empty } from '../components/common'

type EvidencePreview = { text: string; quarantined: boolean; base_revision_id: string; artifact_sha256: string; inline_image_media_type?: 'image/png' | 'image/gif' | 'image/jpeg' | null }
type PendingPreview = { request_id: number; base_revision_id: string; artifact_sha256: string }
const INLINE_IMAGE_TYPES = new Set(['image/png', 'image/gif', 'image/jpeg'])

function Evidence({ session, refreshKey = 0, online = true, writeReady = true, onWriteUnavailable = () => undefined, onWriteAvailable = () => undefined }: { session: Session; refreshKey?: number; online?: boolean; writeReady?: boolean; onWriteUnavailable?: () => void; onWriteAvailable?: () => void }) {
  const [items, setItems] = useState<RecordItem[]>([]); const [selected, setSelected] = useState<RecordItem | null>(null); const [preview, setPreview] = useState<EvidencePreview | null>(null); const [reviewed, setReviewed] = useState(false); const [error, setError] = useState<unknown>(null); const [message, setMessage] = useState(''); const [approving, setApproving] = useState(false); const request = useRef(0); const listRequest = useRef(0); const pagePending = useRef(false); const selectedRef = useRef<RecordItem | null>(null); const previewRef = useRef<EvidencePreview | null>(null); const pendingPreviewRef = useRef<PendingPreview | null>(null); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [nextOffset, setNextOffset] = useState(0); const [hasMore, setHasMore] = useState(false); const [previewLoading, setPreviewLoading] = useState(false); const [imageFailed, setImageFailed] = useState(false); const [retry, setRetry] = useState(0)
  const canWrite = online && writeReady
  function retainSelected(value: RecordItem | null) { selectedRef.current = value; setSelected(value) }
  function retainPreview(value: EvidencePreview | null) { previewRef.current = value; setPreview(value) }
  useEffect(() => { const ticket = ++listRequest.current; pagePending.current = false; setLoading(true); setLoadingMore(false); setError(null); void api.get<{ items: RecordItem[]; total?: number }>('/api/evidence').then(result => { if (ticket !== listRequest.current) return; const active = selectedRef.current; setItems(active && !result.items.some(item => item.id === active.id) ? [...result.items, active] : result.items); setNextOffset(result.items.length); setHasMore(result.total === undefined ? result.items.length === 100 : result.items.length < result.total); const current = active && result.items.find(item => item.id === active.id); if (active && !current) {
      const validation = ++request.current;
      pendingPreviewRef.current = null; retainPreview(null); setPreviewLoading(true); setReviewed(false); setImageFailed(false);
      void api.get<RecordItem>(`/api/records/${active.id}`).then(fresh => {
        if (ticket !== listRequest.current || validation !== request.current || selectedRef.current?.id !== active.id) return;
        if (fresh.kind !== 'upload') throw new Error('Selected evidence is no longer an upload.');
        retainSelected(fresh); setItems(rows => rows.map(row => row.id === fresh.id ? fresh : row));
        void choose(fresh);
      }).catch(err => {
        if (ticket !== listRequest.current || validation !== request.current) return;
        if (err instanceof ApiError && err.status === 404) { retainSelected(null); setItems(rows => rows.filter(row => row.id !== active.id)) }
        setError(err); setPreviewLoading(false);
      });
      return;
    }
    if (!current) return; retainSelected(current); const binding = previewRef.current ?? pendingPreviewRef.current; const unchanged = Boolean(binding && current.revision_id === binding.base_revision_id && current.data.sha256 === binding.artifact_sha256); if (binding && !unchanged) { request.current++; pendingPreviewRef.current = null; retainPreview(null); setPreviewLoading(false); setReviewed(false); setImageFailed(false) } }).catch(err => { if (ticket === listRequest.current) setError(err) }).finally(() => { if (ticket === listRequest.current) setLoading(false) }); return () => { listRequest.current++ } }, [refreshKey, retry])
  async function loadMore() { if (loading || pagePending.current || !hasMore) return; const ticket = listRequest.current; pagePending.current = true; setLoadingMore(true); setError(null); try { const result = await api.get<{ items: RecordItem[]; total?: number }>(`/api/evidence?limit=100&offset=${nextOffset}`); if (ticket !== listRequest.current) return; setItems(old => { const byId = new Map(old.map(item => [item.id, item])); result.items.forEach(item => byId.set(item.id, item)); return [...byId.values()] }); const offset = nextOffset + result.items.length; setNextOffset(offset); setHasMore(result.total === undefined ? result.items.length === 100 : offset < result.total); const active = selectedRef.current; const current = active && result.items.find(item => item.id === active.id); if (current && current.revision_id !== active.revision_id) { retainSelected(current); request.current++; pendingPreviewRef.current = null; retainPreview(null); setPreviewLoading(false); setReviewed(false); setImageFailed(false) } } catch (err) { if (ticket === listRequest.current) setError(err) } finally { if (ticket === listRequest.current) { pagePending.current = false; setLoadingMore(false) } } }
  useEffect(() => () => { request.current++ }, [])
  async function choose(item: RecordItem) { const id = ++request.current; pendingPreviewRef.current = { request_id: id, base_revision_id: item.revision_id, artifact_sha256: String(item.data.sha256 ?? '') }; retainSelected(item); retainPreview(null); setPreviewLoading(true); setImageFailed(false); setReviewed(false); setMessage(''); setError(null); try { const value = await api.get<EvidencePreview>(`/api/evidence/${item.id}/preview`); if (id === request.current) { if (value.base_revision_id && value.artifact_sha256 && item.data.sha256 && (value.base_revision_id !== item.revision_id || value.artifact_sha256 !== item.data.sha256)) throw new Error('Evidence changed while its preview loaded. Refresh the selection.'); pendingPreviewRef.current = null; retainPreview(value) } } catch (err) { if (id === request.current) setError(err) } finally { if (id === request.current) { pendingPreviewRef.current = null; setPreviewLoading(false) } } }
  async function approve() { if (!canWrite || !selected || !reviewed || !preview || preview.quarantined || approving) return; const reviewedPreview = preview; setApproving(true); setMessage('Approving evidence for export…'); setError(null); try { const next = await api.post<RecordItem>(`/api/evidence/${selected.id}/approve-export`, { base_revision_id: reviewedPreview.base_revision_id, artifact_sha256: reviewedPreview.artifact_sha256 }); retainSelected(next); setItems(all => all.map(x => x.id === next.id ? next : x)); setReviewed(false); setMessage('Evidence approved for export.'); onWriteAvailable() } catch (err) { if (err instanceof ApiError && err.status === 503) onWriteUnavailable(); setError(err); setMessage('Approval failed. Retry after reloading the evidence preview.'); if (err instanceof ApiError && err.status === 409) { retainPreview(null); setReviewed(false) } } finally { setApproving(false) } }
  const imageAvailable = Boolean(preview?.inline_image_media_type && INLINE_IMAGE_TYPES.has(preview.inline_image_media_type))
  const canApprove = Boolean(selected && preview && !preview.quarantined && session.user?.role === 'captain' && !selected.data.reviewed_for_export)
  const imageApproved = Boolean(imageAvailable && selected?.data.reviewed_for_export)
  const status = imageAvailable ? imageApproved ? 'Approved local image. Source bytes remain restricted.' : 'Local image available for review. Source bytes remain restricted.' : preview?.quarantined ? 'Quarantined source · export approval is unavailable.' : selected?.data.reviewed_for_export ? 'Reviewed derivative approved for export.' : 'Review a sanitized derivative before approving export.'
  const imageCaption = imageApproved ? 'approved local image' : 'local image available for review'
  return <section><div className="page-head"><div><h1>Evidence</h1><p className="muted">Review the source and approve the derivative you intend to share.</p></div></div><ErrorMessage error={error} />{Boolean(error) && <button onClick={() => setRetry(value => value + 1)}>Retry evidence</button>}{loading && <p role="status">Loading evidence…</p>}<small>{items.length} evidence records loaded from the current host.</small><div className="editor-grid"><aside className="panel">{!loading && !error && !items.length && <Empty title="No evidence yet" body="Import a source file to begin an evidence review." />}{items.map(item => <button key={item.id} className="list-row" onClick={() => void choose(item)}>{String(item.data.filename || item.id)}</button>)}{hasMore && <button disabled={loading || loadingMore} onClick={() => void loadMore()}>{loadingMore ? 'Loading more evidence…' : 'Load more evidence'}</button>}</aside><div className="panel">{selected && preview ? <><p>{status}</p>{imageAvailable && !imageFailed ? <figure className="evidence-image"><img src={`/api/evidence/${selected.id}/render`} alt={String(selected.data.filename ?? selected.id)} onError={() => setImageFailed(true)} /><figcaption>{String(selected.data.filename ?? selected.id)} · {imageCaption}</figcaption></figure> : <>{imageFailed && <p role="status">Image preview could not load. The text preview is shown below. Select the record again to retry.</p>}<pre className="preview">{preview.text}</pre></>}{canApprove && <label><input type="checkbox" disabled={!canWrite || approving} checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed the sanitized derivative</label>}<button disabled={!canWrite || !canApprove || !reviewed || approving} onClick={() => void approve()}>{approving ? 'Approving evidence…' : 'Approve reviewed derivative'}</button>{message && <p role="status" aria-live="polite">{message}</p>}</> : previewLoading ? <p role="status">Loading evidence preview…</p> : selected ? <p className="muted">Evidence preview is unavailable. Select the record again to refresh it.</p> : <Empty title="Select evidence" body="Choose a record to inspect its text." />}</div></div></section>
}
export { Evidence }
