import React, { useEffect, useRef, useState } from 'react'
import { ApiError, api, RecordItem, Session } from '../api'
import { ErrorMessage, Empty } from '../components/common'

type EvidencePreview = { text: string; quarantined: boolean; base_revision_id: string; artifact_sha256: string; inline_image_media_type?: 'image/png' | 'image/gif' | 'image/jpeg' | null }
type PendingPreview = { request_id: number; base_revision_id: string; artifact_sha256: string }
const INLINE_IMAGE_TYPES = new Set(['image/png', 'image/gif', 'image/jpeg'])

function Evidence({ session, refreshKey = 0, online = true, writeReady = true, onWriteUnavailable = () => undefined, onWriteAvailable = () => undefined }: { session: Session; refreshKey?: number; online?: boolean; writeReady?: boolean; onWriteUnavailable?: () => void; onWriteAvailable?: () => void }) {
  const [items, setItems] = useState<RecordItem[]>([]); const [selected, setSelected] = useState<RecordItem | null>(null); const [preview, setPreview] = useState<EvidencePreview | null>(null); const [reviewed, setReviewed] = useState(false); const [error, setError] = useState<unknown>(null); const [message, setMessage] = useState(''); const [approving, setApproving] = useState(false); const request = useRef(0); const selectedRef = useRef<RecordItem | null>(null); const previewRef = useRef<EvidencePreview | null>(null); const pendingPreviewRef = useRef<PendingPreview | null>(null); const [loading, setLoading] = useState(true); const [previewLoading, setPreviewLoading] = useState(false); const [imageFailed, setImageFailed] = useState(false); const [retry, setRetry] = useState(0)
  const canWrite = online && writeReady
  function retainSelected(value: RecordItem | null) { selectedRef.current = value; setSelected(value) }
  function retainPreview(value: EvidencePreview | null) { previewRef.current = value; setPreview(value) }
  useEffect(() => { let cancelled = false; setLoading(true); setError(null); void api.get<{ items: RecordItem[] }>('/api/evidence').then(result => { if (cancelled) return; setItems(result.items); const active = selectedRef.current; const viewed = previewRef.current; const pending = pendingPreviewRef.current; if (!active) return; const current = result.items.find(item => item.id === active.id) ?? null; retainSelected(current); const binding = viewed ?? pending; const unchanged = Boolean(current && binding && current.revision_id === binding.base_revision_id && current.data.sha256 === binding.artifact_sha256); if (binding && !unchanged) { request.current++; pendingPreviewRef.current = null; retainPreview(null); setPreviewLoading(false); setReviewed(false); setImageFailed(false) } }).catch(err => { if (!cancelled) setError(err) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [refreshKey, retry])
  useEffect(() => () => { request.current++ }, [])
  async function choose(item: RecordItem) { const id = ++request.current; pendingPreviewRef.current = { request_id: id, base_revision_id: item.revision_id, artifact_sha256: String(item.data.sha256 ?? '') }; retainSelected(item); retainPreview(null); setPreviewLoading(true); setImageFailed(false); setReviewed(false); setMessage(''); setError(null); try { const value = await api.get<EvidencePreview>(`/api/evidence/${item.id}/preview`); if (id === request.current) { pendingPreviewRef.current = null; retainPreview(value) } } catch (err) { if (id === request.current) setError(err) } finally { if (id === request.current) { pendingPreviewRef.current = null; setPreviewLoading(false) } } }
  async function approve() { if (!canWrite || !selected || !reviewed || !preview || preview.quarantined || approving) return; const reviewedPreview = preview; setApproving(true); setMessage('Approving evidence for export…'); setError(null); try { const next = await api.post<RecordItem>(`/api/evidence/${selected.id}/approve-export`, { base_revision_id: reviewedPreview.base_revision_id, artifact_sha256: reviewedPreview.artifact_sha256 }); retainSelected(next); setItems(all => all.map(x => x.id === next.id ? next : x)); setReviewed(false); setMessage('Evidence approved for export.'); onWriteAvailable() } catch (err) { if (err instanceof ApiError && err.status === 503) onWriteUnavailable(); setError(err); setMessage('Approval failed. Retry after reloading the evidence preview.'); if (err instanceof ApiError && err.status === 409) { retainPreview(null); setReviewed(false) } } finally { setApproving(false) } }
  const imageAvailable = Boolean(preview?.inline_image_media_type && INLINE_IMAGE_TYPES.has(preview.inline_image_media_type))
  const canApprove = Boolean(selected && preview && !preview.quarantined && session.user?.role === 'captain' && !selected.data.reviewed_for_export)
  const imageApproved = Boolean(imageAvailable && selected?.data.reviewed_for_export)
  const status = imageAvailable ? imageApproved ? 'Approved local image. Source bytes remain restricted.' : 'Local image available for review. Source bytes remain restricted.' : preview?.quarantined ? 'Quarantined source · export approval is unavailable.' : selected?.data.reviewed_for_export ? 'Reviewed derivative approved for export.' : 'Review a sanitized derivative before approving export.'
  const imageCaption = imageApproved ? 'approved local image' : 'local image available for review'
  return <section><div className="page-head"><div><h1>Evidence</h1><p className="muted">Review the source and approve the derivative you intend to share.</p></div></div><ErrorMessage error={error} />{Boolean(error) && <button onClick={() => selected ? void choose(selected) : setRetry(value => value + 1)}>Retry evidence</button>}{loading && <p role="status">Loading evidence…</p>}<small>Showing up to 100 evidence records from the current host.</small><div className="editor-grid"><aside className="panel">{!loading && !error && !items.length && <Empty title="No evidence yet" body="Import a source file to begin an evidence review." />}{items.map(item => <button key={item.id} className="list-row" onClick={() => void choose(item)}>{String(item.data.filename || item.id)}</button>)}</aside><div className="panel">{selected && preview ? <><p>{status}</p>{imageAvailable && !imageFailed ? <figure className="evidence-image"><img src={`/api/evidence/${selected.id}/render`} alt={String(selected.data.filename ?? selected.id)} onError={() => setImageFailed(true)} /><figcaption>{String(selected.data.filename ?? selected.id)} · {imageCaption}</figcaption></figure> : <>{imageFailed && <p role="status">Image preview could not load. The text preview is shown below. Select the record again to retry.</p>}<pre className="preview">{preview.text}</pre></>}{canApprove && <label><input type="checkbox" disabled={!canWrite || approving} checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed the sanitized derivative</label>}<button disabled={!canWrite || !canApprove || !reviewed || approving} onClick={() => void approve()}>{approving ? 'Approving evidence…' : 'Approve reviewed derivative'}</button>{message && <p role="status" aria-live="polite">{message}</p>}</> : previewLoading ? <p role="status">Loading evidence preview…</p> : selected ? <p className="muted">Evidence preview is unavailable. Select the record again to refresh it.</p> : <Empty title="Select evidence" body="Choose a record to inspect its text." />}</div></div></section>
}
export { Evidence }
