import React, { useEffect, useRef, useState } from 'react'
import { ApiError, api, Asset, downloadJson, Graph, RecordItem, Session } from '../api'
import { ErrorMessage, Empty, DirtyDialog, Field } from '../components/common'
type EvidencePreview = { text: string; quarantined: boolean; base_revision_id: string; artifact_sha256: string }
function Evidence({ session, refreshKey, online = true }: { session: Session; refreshKey: number; online?: boolean }) {
  const [items, setItems] = useState<RecordItem[]>([]); const [selected, setSelected] = useState<RecordItem | null>(null); const [preview, setPreview] = useState<EvidencePreview | null>(null); const [reviewed, setReviewed] = useState(false); const [error, setError] = useState<unknown>(null); const request = useRef(0); const [loading, setLoading] = useState(true); const [previewLoading, setPreviewLoading] = useState(false); const [retry, setRetry] = useState(0)
  useEffect(() => { let cancelled = false; setLoading(true); setError(null); setPreview(null); setReviewed(false); void api.get<{ items: RecordItem[] }>('/api/evidence').then(r => { if (!cancelled) setItems(r.items) }).catch(err => { if (!cancelled) setError(err) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true; request.current++ } }, [refreshKey, retry])
  async function choose(item: RecordItem) { const id = ++request.current; setSelected(item); setPreview(null); setPreviewLoading(true); setReviewed(false); setError(null); try { const value = await api.get<EvidencePreview>(`/api/evidence/${item.id}/preview`); if (id === request.current) setPreview(value) } catch (err) { if (id === request.current) setError(err) } finally { if (id === request.current) setPreviewLoading(false) } }
  async function approve() { if (!online || !selected || !reviewed || !preview || preview.quarantined) return; const reviewedPreview = preview; try { const next = await api.post<RecordItem>(`/api/evidence/${selected.id}/approve-export`, { base_revision_id: reviewedPreview.base_revision_id, artifact_sha256: reviewedPreview.artifact_sha256 }); setSelected(next); setItems(all => all.map(x => x.id === next.id ? next : x)); setPreview(null); setReviewed(false) } catch (err) { setError(err); if (err instanceof ApiError && err.status === 409) { setPreview(null); setReviewed(false) } } }
  const canApprove = Boolean(selected && preview && !preview.quarantined && session.user?.role === 'captain' && !selected.data.reviewed_for_export)
  return <section><div className="page-head"><div><h1>Evidence</h1><p className="muted">Review the source and approve the derivative you intend to share.</p></div></div><ErrorMessage error={error} />{Boolean(error) && <button onClick={() => selected ? void choose(selected) : setRetry(value => value + 1)}>Retry evidence</button>}{loading && <p role="status">Loading evidence…</p>}<small>Showing up to 100 evidence records from the current host.</small><div className="editor-grid"><aside className="panel">{!loading && !error && !items.length && <Empty title="No evidence yet" body="Import a source file to begin an evidence review." />}{items.map(item => <button key={item.id} className="list-row" onClick={() => void choose(item)}>{String(item.data.filename || item.id)}</button>)}</aside><div className="panel">{selected && preview ? <><p>{preview.quarantined ? 'Quarantined source · export approval is unavailable.' : selected.data.reviewed_for_export ? 'Reviewed derivative approved for export.' : 'Review a sanitized derivative before approving export.'}</p><pre className="preview">{preview.text}</pre>{canApprove && <label><input type="checkbox" disabled={!online} checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed the sanitized derivative</label>}<button disabled={!online || !canApprove || !reviewed} onClick={() => void approve()}>Approve reviewed derivative</button></> : previewLoading ? <p role="status">Loading evidence preview…</p> : selected ? <p className="muted">Evidence preview is unavailable. Select the record again to refresh it.</p> : <Empty title="Select evidence" body="Choose a record to inspect its text." />}</div></div></section>
}
export { Evidence }
