import React, { useEffect, useRef, useState } from 'react'
import { ApiError, api, Asset, downloadJson, Graph, RecordItem, Session } from '../api'
import { ErrorMessage, Empty, DirtyDialog, Field } from '../components/common'
type Upload = RecordItem & { data: { filename?: string; format?: string; status?: string; limitations?: string[]; sha256?: string; size?: number } }
type MergeBinding = { upload_revision_id: string; preview_revision_id: string; preview_hash: string }
type UploadPreview = { _review: MergeBinding; assets: unknown[]; relationships: unknown[]; observations: unknown[]; limitations: string[]; complete: boolean }
function Imports({ refreshKey, online = true }: { refreshKey: number; online?: boolean }) {
  const [items, setItems] = useState<Upload[]>([]); const [file, setFile] = useState<File | null>(null); const [format, setFormat] = useState('manual_json'); const [selected, setSelected] = useState<Upload | null>(null); const [preview, setPreview] = useState<UploadPreview | null>(null); const [binding, setBinding] = useState<MergeBinding | null>(null); const [error, setError] = useState<unknown>(null); const [parsing, setParsing] = useState(false); const request = useRef(0); const [loading, setLoading] = useState(true); const [retry, setRetry] = useState(0)
  useEffect(() => { let cancelled = false; setLoading(true); setError(null); setPreview(null); setBinding(null); void api.get<{ items: Upload[] }>('/api/uploads').then(r => { if (!cancelled) setItems(r.items) }).catch(err => { if (!cancelled) setError(err) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [refreshKey, retry])
  function choose(item: Upload) { if (parsing) return; request.current++; setSelected(item); setPreview(null); setBinding(null) }
  async function upload() { if (!online || !file || parsing) return; try { const form = new FormData(); form.append('file', file); form.append('format', format); const item = await api.post<Upload>('/api/uploads', form); setItems(old => [item, ...old]); setSelected(item); setPreview(null); setBinding(null); setFile(null) } catch (err) { setError(err) } }
  async function parse() { if (!online || !selected || parsing) return; const number = ++request.current; const item = selected; setParsing(true); setPreview(null); setBinding(null); setError(null); try { const updated = await api.post<Upload>(`/api/uploads/${item.id}/parse`); setSelected(updated); setItems(old => old.map(x => x.id === updated.id ? updated : x)); const value = await api.get<UploadPreview>(`/api/uploads/${updated.id}/preview`); if (number === request.current) { setPreview(value); setBinding(value._review) } } catch (err) { if (number === request.current) setError(err) } finally { if (number === request.current) setParsing(false) } }
  async function merge() { if (!online || !selected || !preview || !binding || parsing) return; try { const item = await api.post<Upload>(`/api/uploads/${selected.id}/merge`, binding); setSelected(item); setItems(old => old.map(x => x.id === item.id ? item : x)); setPreview(null); setBinding(null) } catch (err) { setError(err); if (err instanceof ApiError && err.status === 409) { setPreview(null); setBinding(null) } } }
  return <section><div className="page-head"><div><h1>Imports</h1><p className="muted">Upload an existing source. Inspect the preview before merging its records.</p></div></div><div className="split"><div className="panel"><label>Format<select value={format} onChange={e => { setFormat(e.target.value); setPreview(null); setBinding(null) }}>{['nmap_xml', 'nmap_text', 'nmap_gnmap', 'zap_json', 'har', 'burp_xml', 'linpeas_text', 'winpeas_text', 'bloodhound', 'manual_json'].map(v => <option key={v}>{v}</option>)}</select></label><label>File<input type="file" disabled={!online} onChange={e => { setFile(e.target.files?.[0] ?? null); setPreview(null); setBinding(null) }} /></label><button className="primary" disabled={!online || !file || parsing} onClick={() => void upload()}>Upload source</button></div><div className="panel"><ErrorMessage error={error} />{loading && <p role="status">Loading imports…</p>}{Boolean(error) && <button onClick={() => setRetry(value => value + 1)}>Retry imports</button>}{!loading && !error && !items.length && <Empty title="No imports yet" body="Choose a source file to create its first preview." />}<small>Showing up to 100 source files.</small>{items.map(item => <button key={item.id} disabled={parsing} className="list-row" onClick={() => choose(item)}><span><strong>{item.data.filename ?? item.id}</strong><small>{item.data.format} · {item.data.status}</small></span></button>)}</div></div>{selected && <div className="panel"><div className="actions"><button aria-live="polite" disabled={!online || parsing} onClick={() => void parse()}>{parsing ? 'Parsing preview…' : 'Parse preview'}</button><button className="primary" disabled={!online || parsing || !preview || !binding} onClick={() => void merge()}>Merge records</button></div>{preview ? <pre className="preview">{JSON.stringify(preview, null, 2)}</pre> : <p>{parsing ? 'Parsing source in a contained preview…' : 'Preview output appears here after parsing.'}</p>}</div>}</section>
}
export { Imports }
